###
POST http://localhost:9000/api/cursos
Content-Type: application/json

{
  "codigo": "iff",
  "nombre": "MINooooooooooooooooooS ",
  "tipo": "teórico",
  "categoria": "EEEP",
  "grupo": "A",
  "creditos": 4
}


###
GET http://localhost:9000/api/cursos HTTP/1.1

###
GET http://localhost:9000/api/cursos/63055d2402a85f30145412e0

###
PUT http://localhost:9000/api/cursos/63055d2402a85f30145412e0
Content-Type: application/json

{
  "grupo": "A"
}

###
DELETE http://localhost:9000/api/cursos/63055e57844563c2dff64197
